version: "3.8"

services:
  server:
    build:
      context: ./server
      args:
        APP_PORT: 8080
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8080
    ports:
      - "8080:8080" # Maps server server to localhost:8080
    networks:
      - default

  client:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: http://localhost:8080
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Maps SolidJS app to localhost:3000
    depends_on:
      - server
    networks:
      - default

networks:
  default:
    name: vm-project